# Generated by Django 5.2.6 on 2025-09-14 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Font",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "font_name",
                    models.CharField(max_length=100, verbose_name="اسم الخط"),
                ),
                (
                    "designer",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="المصمم"
                    ),
                ),
                (
                    "font_file",
                    models.FileField(upload_to="font_files/", verbose_name="ملف الخط"),
                ),
                (
                    "font_type",
                    models.CharField(
                        choices=[("serif", "Serif"), ("sans-serif", "Sans Serif")],
                        max_length=20,
                        verbose_name="فصيلة الخط",
                    ),
                ),
                (
                    "language_support",
                    models.CharField(
                        choices=[
                            ("arabic_only", "عربي فقط"),
                            ("latin_only", "لاتيني فقط"),
                            ("bilingual", "ثنائي اللغة"),
                        ],
                        max_length=20,
                        verbose_name="الدعم اللغوي",
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("standard", "خط قياسي"),
                            ("dyslexia-friendly", "خط مصمم لعسر القراءة"),
                        ],
                        default="standard",
                        max_length=30,
                        verbose_name="تصنيف الخط",
                    ),
                ),
                (
                    "upload_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الرفع"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Criterion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criterion_name",
                    models.CharField(max_length=200, verbose_name="اسم المعيار"),
                ),
                (
                    "metric_key",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="المفتاح البرمجي"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="الوصف"),
                ),
                ("ideal_value", models.FloatField(verbose_name="القيمة المثالية")),
                (
                    "weight",
                    models.FloatField(default=1.0, verbose_name="الأهمية (الوزن)"),
                ),
                (
                    "language_scope",
                    models.CharField(
                        choices=[
                            ("general", "عام"),
                            ("arabic", "عربي فقط"),
                            ("latin", "لاتيني فقط"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="نطاق اللغة",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnalysisResult",
            fields=[
                (
                    "font",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="fonts.font",
                        verbose_name="الخط",
                    ),
                ),
                ("final_score", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
