# Generated by Django 5.2.6 on 2025-09-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fonts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisresult",
            name="arabic_ascender_consistency",
            field=models.FloatField(
                blank=True, null=True, verbose_name="اتساق الصواعد (عربي)"
            ),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="arabic_descender_consistency",
            field=models.FloatField(
                blank=True, null=True, verbose_name="اتساق الهوابط (عربي)"
            ),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="arabic_kerning_quality",
            field=models.FloatField(
                blank=True, null=True, verbose_name="جودة التقنين (عربي)"
            ),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="ascender_height",
            field=models.FloatField(
                blank=True, null=True, verbose_name="ارتفاع الصواعد"
            ),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="balance_consistency",
            field=models.FloatField(
                blank=True, null=True, verbose_name="اتساق توازن الحروف"
            ),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="cap_height",
            field=models.FloatField(
                blank=True, null=True, verbose_name="ارتفاع الحرف الكبير"
            ),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="descender_depth",
            field=models.FloatField(blank=True, null=True, verbose_name="عمق الهوابط"),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="diacritic_consistency",
            field=models.FloatField(
                blank=True, null=True, verbose_name="اتساق مواضع التشكيل"
            ),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="final_consistency",
            field=models.FloatField(
                blank=True, null=True, verbose_name="اتساق الأشكال النهائية"
            ),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="initial_consistency",
            field=models.FloatField(
                blank=True, null=True, verbose_name="اتساق الأشكال الابتدائية"
            ),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="isolated_consistency",
            field=models.FloatField(
                blank=True, null=True, verbose_name="اتساق الأشكال المنفردة"
            ),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="latin_ascender_consistency",
            field=models.FloatField(
                blank=True, null=True, verbose_name="اتساق الصواعد (لاتيني)"
            ),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="latin_descender_consistency",
            field=models.FloatField(
                blank=True, null=True, verbose_name="اتساق الهوابط (لاتيني)"
            ),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="latin_kerning_quality",
            field=models.FloatField(
                blank=True, null=True, verbose_name="جودة التقنين (لاتيني)"
            ),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="medial_consistency",
            field=models.FloatField(
                blank=True, null=True, verbose_name="اتساق الأشكال الوسطية"
            ),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="score_for_sans_serif",
            field=models.FloatField(
                blank=True, null=True, verbose_name="درجة Sans Serif"
            ),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="score_for_serif",
            field=models.FloatField(blank=True, null=True, verbose_name="درجة Serif"),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="sidebearing_consistency",
            field=models.FloatField(
                blank=True, null=True, verbose_name="اتساق الهوامش الجانبية"
            ),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="space_width_ratio",
            field=models.FloatField(
                blank=True, null=True, verbose_name="نسبة عرض الفراغ"
            ),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="width_consistency",
            field=models.FloatField(
                blank=True, null=True, verbose_name="اتساق عرض الحروف"
            ),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="x_height",
            field=models.FloatField(blank=True, null=True, verbose_name="ارتفاع حرف x"),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="xheight_ratio",
            field=models.FloatField(
                blank=True, null=True, verbose_name="نسبة ارتفاع x"
            ),
        ),
        migrations.AlterField(
            model_name="analysisresult",
            name="final_score",
            field=models.FloatField(
                blank=True, null=True, verbose_name="الدرجة النهائية"
            ),
        ),
    ]
