# Generated by Django 5.2.6 on 2025-09-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fonts", "0002_analysisresult_arabic_ascender_consistency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisresult",
            name="width_histogram",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="analysis_reports/",
                verbose_name="رسم توزيع العرض",
            ),
        ),
    ]
