# Generated by Django 5.2.6 on 2025-09-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fonts", "0003_analysisresult_width_histogram"),
    ]

    operations = [
        migrations.AddField(
            model_name="criterion",
            name="lower_is_better",
            field=models.BooleanField(
                default=False, verbose_name="هل القيمة الأقل أفضل؟"
            ),
        ),
    ]
