# Generated by Django 5.2.6 on 2025-09-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fonts", "0004_criterion_lower_is_better"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysisresult",
            name="arabic_kerning_quality",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="جودة التقنين (عربي)"
            ),
        ),
        migrations.AlterField(
            model_name="analysisresult",
            name="latin_kerning_quality",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="جودة التقنين (لاتيني)"
            ),
        ),
    ]
